name: Build and Deploy ASP.NET MVC 4.8 to IIS

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Restore NuGet packages
        run: nuget restore FirstWebApp.sln

      - name: Build and Publish
        run: |
          msbuild FirstWebApp/FirstWebApp.csproj `
            /p:Configuration=Release `
            /p:DeployOnBuild=true `
            /p:WebPublishMethod=FileSystem `
            /p:PublishUrl=published

      - name: Download PuTTY SCP and SSH tools
        run: |
          Invoke-WebRequest https://the.earth.li/~sgtatham/putty/latest/w64/pscp.exe -OutFile pscp.exe
          Invoke-WebRequest https://the.earth.li/~sgtatham/putty/latest/w64/plink.exe -OutFile plink.exe

      - name: Write SSH private key
        run: |
          $env:SSH_PRIVATE_KEY | Out-File -FilePath "id_rsa" -Encoding ascii
          icacls id_rsa /inheritance:r
          icacls id_rsa /grant:r "$env:USERNAME:R"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy published files via SCP
        run: |
          .\pscp.exe -i id_rsa -r .\published\* ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:"C:\Users\HP\Documents\dotnet-publish"

      - name: Restart IIS site via SSH
        run: |
          .\plink.exe -i id_rsa -batch ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "powershell -Command `"Import-Module WebAdministration; Restart-WebSite -Name '${{ secrets.IIS_SITE_NAME }}'`""
