name: Build and Deploy ASP.NET MVC 4.8 to IIS

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and Deploy to Remote IIS Server
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Restore NuGet packages
        run: nuget restore FirstWebApp.sln

      - name: Build and publish the project
        run: |
          msbuild FirstWebApp/FirstWebApp.csproj `
            /p:Configuration=Release `
            /p:DeployOnBuild=true `
            /p:WebPublishMethod=FileSystem `
            /p:PublishUrl=published

      - name: Copy published files to IIS server via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "published/*"
          target: "C:/Users/HP/Documents/dotnet-publish"

      - name: Restart IIS site via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            Import-Module WebAdministration
            Restart-WebSite -Name "${{ secrets.IIS_SITE_NAME }}"
