name: Build & Deploy ASP.NET MVC 4.8 to IIS

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Restore NuGet packages
        run: nuget restore FirstWebApp.sln

      - name: Build and publish to local folder
        run: |
          $publishDir = "$env:GITHUB_WORKSPACE\publish"
          msbuild FirstWebApp\FirstWebApp.csproj `
            /p:Configuration=Release `
            /p:DeployOnBuild=true `
            /p:WebPublishMethod=FileSystem `
            /p:PublishProvider=FileSystem `
            /p:PublishDir=$publishDir\

      - name: Compress published output
        run: |
          $publishPath = "$env:GITHUB_WORKSPACE\publish"
          if (-Not (Test-Path $publishPath)) {
            throw "Publish output folder not found: $publishPath"
          }
          Compress-Archive -Path "$publishPath\*" -DestinationPath "$env:GITHUB_WORKSPACE\publish.zip"

      - name: Download PuTTY tools
        run: |
          Invoke-WebRequest https://the.earth.li/~sgtatham/putty/latest/w64/pscp.exe -OutFile pscp.exe
          Invoke-WebRequest https://the.earth.li/~sgtatham/putty/latest/w64/plink.exe -OutFile plink.exe

      - name: Write SSH private key
        shell: powershell
        run: |
          $keyPath = "$env:GITHUB_WORKSPACE\id_rsa"
          Set-Content -Path $keyPath -Value "${{ secrets.SSH_PRIVATE_KEY }}" -NoNewline
          icacls $keyPath /inheritance:r
          icacls $keyPath /grant:r "$($env:USERNAME):(R)"

      - name: Upload publish.zip to IIS server
        run: |
          .\pscp.exe -i id_rsa publish.zip ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:"C:\Users\HP\Documents\publish.zip"


      - name: Unzip and replace IIS site contents
        run: |
          .\plink.exe -i id_rsa -batch ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} `
            "powershell -Command `
              \"Expand-Archive -Force -Path 'C:\Users\HP\Documents\publish.zip' -DestinationPath 'C:\Users\HP\Documents\dotnet-publish'; `
              Import-Module WebAdministration; `
              Restart-WebSite -Name '${{ secrets.IIS_SITE_NAME }}'\""
