name: Build & Deploy ASP.NET MVC 4.8 to IIS

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Restore NuGet packages
        run: nuget restore FirstWebApp.sln

      - name: Build and publish to flat folder (raw output)
        run: |
          $publishDir = "$env:GITHUB_WORKSPACE\publish"
          msbuild FirstWebApp\FirstWebApp.csproj `
            /t:Build `
            /p:Configuration=Release `
            /p:OutputPath=$publishDir
      
          if (Test-Path $publishDir) {
            Write-Host "✅ Publish folder created at: $publishDir"
            Get-ChildItem -Recurse $publishDir
          } else {
            Write-Host "❌ Publish folder NOT created!"
            throw "Publish output folder not found: $publishDir"
          }

      - name: Show contents of publish folder
        shell: powershell
        run: |
          $publishDir = "$env:GITHUB_WORKSPACE\publish"
          if (Test-Path $publishDir) {
            Write-Host "`n✅ Publish folder created at: $publishDir"
            Get-ChildItem -Path $publishDir -Recurse | Format-List
            Write-Host "`n`nStructured view with tree layout:`n"
            Get-ChildItem -Path $publishDir -Recurse
          } else {
            Write-Host "❌ Publish folder not found: $publishDir"
            throw "Missing publish folder."
          }


      - name: Debug - List possible publish folders
        run: |
          Write-Host "GitHub Workspace: $env:GITHUB_WORKSPACE"
          Get-ChildItem -Recurse "$env:GITHUB_WORKSPACE" | Where-Object { $_.PSIsContainer -and $_.Name -like "*publish*" }

      - name: Compress published output
        run: |
          $publishDir = "$env:GITHUB_WORKSPACE\publish\_PublishedWebsites\FirstWebApp"
          if (-Not (Test-Path $publishDir)) {
            throw "Expected publish output not found: $publishDir"
          }
          Compress-Archive -Path "$publishDir\*" -DestinationPath "$env:GITHUB_WORKSPACE\publish.zip"


      - name: Download PuTTY tools
        run: |
          Invoke-WebRequest https://the.earth.li/~sgtatham/putty/latest/w64/pscp.exe -OutFile pscp.exe
          Invoke-WebRequest https://the.earth.li/~sgtatham/putty/latest/w64/plink.exe -OutFile plink.exe

      - name: Write SSH private key
        shell: powershell
        run: |
          $keyPath = "$env:GITHUB_WORKSPACE\id_rsa"
          Set-Content -Path $keyPath -Value "${{ secrets.SSH_PRIVATE_KEY }}" -NoNewline
          icacls $keyPath /inheritance:r
          icacls $keyPath /grant:r "$($env:USERNAME):(R)"

      - name: Upload publish.zip to IIS server
        shell: powershell
        run: |
          $username = "${{ secrets.SSH_USERNAME }}"
          $remoteHost = "${{ secrets.SSH_HOST }}"
          $remotePath = 'C:\Users\HP\Documents\publish.zip'
      
          if (-not $username -or -not $remoteHost) {
            throw "SSH_USERNAME or SSH_HOST is missing. Check your GitHub secrets."
          }
      
          $destination = "$($username)@$($remoteHost):`"$remotePath`""
          Write-Host "Uploading to $destination"
      
          .\pscp.exe -i id_rsa publish.zip $destination




      - name: Unzip and restart IIS
        run: |
          .\plink.exe -i id_rsa -batch ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} `
            "powershell -Command `
              \"Expand-Archive -Force -Path 'C:\Users\HP\Documents\publish.zip' -DestinationPath 'C:\Users\HP\Documents\dotnet-publish'; `
              Import-Module WebAdministration; `
              Restart-WebSite -Name '${{ secrets.IIS_SITE_NAME }}'\""
