name: Build & Deploy .NET Framework 4.8 to IIS via SSH

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Restore NuGet packages
        run: nuget restore FirstWebApp.sln

      - name: Build & Publish using MSBuild
        run: |
          msbuild FirstWebApp/FirstWebApp.csproj `
            /p:Configuration=Release `
            /p:DeployOnBuild=true `
            /p:WebPublishMethod=FileSystem `
            /p:PublishUrl=publish

      - name: Compress published output
        run: Compress-Archive -Path publish\* -DestinationPath publish.zip

      - name: Setup SSH key
        shell: powershell
        run: |
          mkdir $HOME\.ssh
          Set-Content -Path $HOME\.ssh\id_rsa -Value "${{ secrets.SSH_PRIVATE_KEY }}" -NoNewline
          & icacls "$HOME\.ssh\id_rsa" /inheritance:r
          & icacls "$HOME\.ssh\id_rsa" /grant:r "$($env:USERNAME):(R)"

      - name: Upload publish.zip via SSH
        run: |
          Invoke-WebRequest -Uri https://the.earth.li/~sgtatham/putty/latest/w64/pscp.exe -OutFile pscp.exe
          .\pscp.exe -i $HOME\.ssh\id_rsa publish.zip ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:"C:\Users\HP\Documents\publish.zip"

      - name: Unzip and Restart IIS on server
        run: |
          Invoke-WebRequest -Uri https://the.earth.li/~sgtatham/putty/latest/w64/plink.exe -OutFile plink.exe
          .\plink.exe -i $HOME\.ssh\id_rsa -batch ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} `
            "powershell -Command `"Expand-Archive -Force -Path 'C:\Users\HP\Documents\publish.zip' -DestinationPath 'C:\Users\HP\Documents\dotnet-publish'; Import-Module WebAdministration; Restart-WebSite -Name '${{ secrets.IIS_SITE_NAME }}'`""
