name: Build and Deploy .NET Framework MVC to IIS

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build on GitHub-hosted Runner
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore NuGet packages
        run: nuget restore FirstWebApp.sln

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Build and Publish to Folder
        shell: powershell
        run: |
          $publishDir = "$env:GITHUB_WORKSPACE\publish"
          msbuild FirstWebApp\FirstWebApp.csproj `
            /t:Build `
            /p:Configuration=Release `
            /p:OutputPath=$publishDir

          Write-Host "`n✅ Publish folder created at: $publishDir"
          Get-ChildItem -Path $publishDir | Format-Table Mode, LastWriteTime, Length, Name -AutoSize

      - name: Upload Published Output as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: publish/

  deploy:
    name: Deploy to IIS on Self-hosted Server
    needs: build
    runs-on: self-hosted

    steps:
      - name: Download Published Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: ./publish

      - name: Stop IIS
        shell: cmd
        run: powershell -ExecutionPolicy Bypass -Command "iisreset /stop"


      - name: Set source path and copy files
        shell: cmd
        run: |
          set source=%GITHUB_WORKSPACE%\publish\_PublishedWebsites\FirstWebApp
          xcopy /s /y "%source%\*" "C:\Users\HP\Documents\dotnet-publish\"




      - name: Start IIS
        shell: cmd
        run: powershell -ExecutionPolicy Bypass -Command "iisreset /start"

